version: "3.3"

services:
  nginx:
    container_name: cms
    build:
      context: ./frontend/
      dockerfile: ./apps/cms/Dockerfile
    volumes:
      - ${MEDIA_FOLDER}:/app/backend/algocount/media/
    ports:
      - ${PORT_OUT}:80
    depends_on:
      - api
    restart: "on-failure"

  db:
    image: postgres
    volumes:
      - ${DB_FOLDER}:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres

  api:
    build: .
    volumes:
      - ${MEDIA_FOLDER}:/app/backend/algocount/media/
    entrypoint: ["/bin/sh", "-c"]
    command:
      - |
        python3 manage.py migrate --settings=algocount.settings.production
        gunicorn --workers=2 --threads=4  algocount.wsgi:application --bind 0.0.0.0:8000
    expose:
      - 8000
    depends_on:
      - db
    restart: on-failure 
