version: "3.3"
services:
  nginx:
      build: nginx

      container_name:
        timon_nginx

      ports:
        - 8000:80
      # volumes:
      #   - static_volume:/home/timon/static

      depends_on:
        - web
      restart: "on-failure"
  db:
    image: postgres
    volumes:
      - ../data/db:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
  web:
    build: .
    command:  "gunicorn algocount.wsgi:application --bind 0.0.0.0:8000"
    expose:
      - 8000
    depends_on:
      - db
