version: "3.3"
services:
  nginx:
    build:
      context: ./
      dockerfile: nginx/Dockerfile

    container_name: timon_nginx
    volumes:
      - media:/home/pn/app/backend/algocount/media/
    ports:
      - 3001:80

    depends_on:
      - web
    restart: "on-failure"
  db:
    image: postgres
    volumes:
      - ../data/db:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
  web:
    build: .
    volumes:
      - media:/home/pn/app/backend/algocount/media/
    command:
      bash -c  "python manage.py migrate --settings=algocount.settings.production &&
      gunicorn --access-logfile '/var/log/gunicorn/access.log' --error-logfile '/var/log/gunicorn/error.log' algocount.wsgi:application --bind 0.0.0.0:8000 "
    expose:
      - 8000
    depends_on:
      - db
volumes:
  media:
