# Generated by Django 3.2.8 on 2021-11-08 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='glossarycategory',
            name='title',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='glossaryterm',
            name='more_info_url',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
