# Generated by Django 3.2.8 on 2021-10-18 13:02

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0003_auto_20211018_1223'),
    ]

    operations = [
        migrations.AlterField(
            model_name='experiment',
            name='context',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='experiment',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='experiment',
            name='disclaimers',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.TextField(), blank=True, null=True, size=None),
        ),
        migrations.AlterField(
            model_name='experiment',
            name='experiment_setup',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='experiment',
            name='findings',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='experiment',
            name='order',
            field=models.SmallIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='experiment',
            name='research_question',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
