# Generated by Django 3.2.8 on 2021-10-21 06:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0004_auto_20211018_1502'),
    ]

    operations = [
        migrations.CreateModel(
            name='GlossaryCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('last_update', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('color', models.CharField(max_length=10)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cms.project')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.RenameField(
            model_name='step',
            old_name='order',
            new_name='step_number',
        ),
        migrations.CreateModel(
            name='GlossaryTerm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('last_update', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('more_info_url', models.TextField()),
                ('glossary_category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='cms.glossarycategory')),
                ('image', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='cms.projectmedia')),
                ('related', models.ManyToManyField(related_name='_cms_glossaryterm_related_+', to='cms.GlossaryTerm')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
