# Generated by Django 3.2.8 on 2021-11-09 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0004_alter_experiment_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectmedia',
            name='type',
            field=models.CharField(choices=[('image', 'Image'), ('file', 'File')], default='image', max_length=10),
        ),
    ]
