# Generated by Django 3.2.8 on 2021-11-10 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0005_projectmedia_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectuser',
            name='level',
            field=models.CharField(choices=[('1', 'Author'), ('2', 'Editor')], default='2', max_length=1),
        ),
        migrations.AlterField(
            model_name='step',
            name='content',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
