# Generated by Django 3.2.8 on 2021-11-10 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0006_auto_20211110_1705'),
    ]

    operations = [
        migrations.AlterField(
            model_name='glossaryterm',
            name='more_info_url',
            field=models.TextField(blank=True, null=True),
        ),
    ]
