# Generated by Django 3.2.8 on 2021-10-21 14:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0006_auto_20211021_1510'),
    ]

    operations = [
        migrations.AlterField(
            model_name='glossaryterm',
            name='glossary_category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='cms.glossarycategory'),
            preserve_default=False,
        ),
    ]
