# Generated by Django 3.2.8 on 2021-10-21 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0007_alter_glossaryterm_glossary_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='glossaryterm',
            name='more_info_url',
            field=models.TextField(blank=True, null=True),
        ),
    ]
