# Generated by Django 3.2.8 on 2021-12-14 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0008_remove_experiment_disclaimers'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='language',
            field=models.CharField(choices=[('IT', 'Italian'), ('EN', 'English')], default='2', max_length=2),
        ),
    ]
