# Generated by Django 3.2.8 on 2021-12-14 13:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0009_project_language'),
    ]

    operations = [
        migrations.AddField(
            model_name='glossarycategory',
            name='project',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='cms.project'),
        ),
        migrations.AlterField(
            model_name='project',
            name='language',
            field=models.CharField(choices=[('it', 'Italian'), ('en', 'English')], default='en', max_length=2),
        ),
        migrations.AlterField(
            model_name='projectuser',
            name='level',
            field=models.CharField(choices=[('1', 'Author'), ('2', 'Collaborator')], default='2', max_length=1),
        ),
    ]
