# Generated by Django 3.2.8 on 2021-12-15 13:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0011_reference'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reference',
            name='authors',
        ),
        migrations.RemoveField(
            model_name='reference',
            name='source',
        ),
    ]
