# Generated by Django 3.2.8 on 2021-11-04 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0012_experiment_cover'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='experiments_description',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='long_description',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='short_description',
            field=models.TextField(null=True),
        ),
    ]
