# Generated by Django 3.2.8 on 2021-12-16 10:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0013_auto_20211215_1719'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='reference',
            options={'ordering': ['description']},
        ),
    ]
