# Generated by Django 3.2.8 on 2021-11-05 08:02

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cms', '0013_auto_20211104_1046'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='projectuser',
            unique_together={('user', 'project')},
        ),
    ]
