# Generated by Django 3.2.8 on 2021-12-21 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0015_stepdownload'),
    ]

    operations = [
        migrations.AlterField(
            model_name='experiment',
            name='cover',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='glossaryterm',
            name='image',
            field=models.TextField(blank=True, null=True),
        ),
    ]
