# Generated by Django 3.2.8 on 2021-12-21 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0016_auto_20211221_0901'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='footer',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
