# Generated by Django 3.2.8 on 2022-01-21 14:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0017_project_footer'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='reference',
            options={},
        ),
        migrations.AlterUniqueTogether(
            name='glossarycategory',
            unique_together={('title', 'project')},
        ),
    ]
