# Generated by Django 3.2.8 on 2022-01-21 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0018_auto_20220121_1526'),
    ]

    operations = [
        migrations.AlterField(
            model_name='glossarycategory',
            name='title',
            field=models.CharField(max_length=50),
        ),
    ]
