# Generated by Django 3.2.8 on 2022-01-24 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0021_alter_glossaryterm_more_info_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='glossaryterm',
            name='more_info_url',
            field=models.TextField(blank=True, null=True),
        ),
    ]
