# Generated by Django 3.2.8 on 2022-01-24 15:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0024_alter_glossaryterm_more_info_url'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='step',
            unique_together={('experiment', 'step_number')},
        ),
    ]
