# Generated by Django 3.2.8 on 2022-01-26 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0025_alter_step_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='project_explanation',
            field=models.TextField(null=True),
        ),
    ]
