# Generated by Django 3.2.8 on 2022-01-26 15:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0027_experiment_pdf_report'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExperimentAdditionalMaterial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('last_update', models.DateTimeField(auto_now=True)),
                ('title', models.TextField()),
                ('file', models.FileField(upload_to='')),
                ('experiment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cms.experiment')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
