# Generated by Django 3.2.8 on 2022-01-26 16:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0028_experimentadditionalmaterial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='experimentadditionalmaterial',
            name='title',
        ),
    ]
