# Generated by Django 3.2.8 on 2022-03-12 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0029_remove_experimentadditionalmaterial_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectmedia',
            name='type',
            field=models.CharField(choices=[('image', 'Image'), ('file', 'File'), ('video', 'Video')], default='image', max_length=10),
        ),
    ]
