# Generated by Django 3.2.8 on 2022-05-17 08:36

import cms.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0036_alter_step_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectmedia',
            name='file',
            field=models.FileField(upload_to=cms.models.get_upload_path),
        ),
    ]
