# Generated by Django 3.2.8 on 2022-05-18 06:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0038_auto_20220518_0857'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='glossarycategory',
            unique_together={('title', 'project')},
        ),
    ]
