# Generated by Django 3.2.8 on 2022-05-19 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0039_alter_glossarycategory_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='reference',
            name='in_text_citation',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
