# Generated by Django 3.2.8 on 2022-05-20 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0040_reference_in_text_citation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectmedia',
            name='type',
            field=models.CharField(choices=[('image', 'Image'), ('video', 'Video'), ('file', 'Generic file')], default='image', max_length=10),
        ),
        migrations.AlterField(
            model_name='projectuser',
            name='level',
            field=models.CharField(choices=[('1', 'Author'), ('2', 'Collaborator'), ('3', 'Viewer')], default='2', max_length=1),
        ),
    ]
