# Generated by Django 3.2.8 on 2022-05-20 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0041_auto_20220520_1645'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='last_build',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='project',
            name='last_build_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
