# Generated by Django 3.2.8 on 2022-05-23 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0042_auto_20220520_1849'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='last_update',
            field=models.DateTimeField(),
        ),
    ]
