# Generated by Django 3.2.8 on 2022-05-23 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0043_alter_project_last_update'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='base_path_build',
            field=models.TextField(blank=True, null=True),
        ),
    ]
