# Generated by Django 3.2.8 on 2022-05-23 13:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0044_project_base_path_build'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='experiment',
            options={'ordering': ['order']},
        ),
        migrations.AlterModelOptions(
            name='step',
            options={'ordering': ['step_number']},
        ),
        migrations.AlterUniqueTogether(
            name='step',
            unique_together=set(),
        ),
    ]
