# Generated by Django 3.2.8 on 2022-05-26 07:10

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0045_auto_20220523_1559'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='cover_images',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.TextField(), blank=True, default=[], size=None),
            preserve_default=False,
        ),
    ]
