#!/bin/bash

set -o errexit
set -o pipefail
set -o nounset

python3 backend/algocount/manage.py migrate --settings=algocount.settings.production

/usr/local/bin/gunicorn  --chdir backend/algocount  algocount.wsgi:application --bind 0.0.0.0:8000 --timeout 600